version: '3'

services:
  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: 'repeat-bot-worker'
    restart: always
    volumes:
      - .:/app/
    networks:
      - tier

networks:
  tier:
    external:
      name: telegram-bots-network