version: '3'

services:

  repeat-nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: 'repeat-bot-nginx'
    restart: always
    ports:
      - "8980:80"
    volumes:
      - .:/app/
    networks:
      - tier
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  repeat:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: 'repeat-bot-php'
    restart: always
    volumes:
      - ${MP3_PATH}:/app/words
      - .:/app/
    networks:
      - tier
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: 'repeat-bot-worker'
    restart: always
    volumes:
      - .:/app/
    networks:
      - tier
    logging:
      options:
        max-size: "10m"

  mysql:
    image: mysql:5.7.22
    container_name: 'telegram-bots-mysql'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: '%'
    #    volumes:
    #      - ./docker/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - tier

  redis:
    container_name: 'telegram-bots-redis'
    image: redis:3.2
    restart: always
    ports:
      - "127.0.0.1:6379:6379/tcp"
    networks:
      - tier

volumes:
  filters:
    driver: local
  proxy-profiles:
    driver: local

networks:
  tier: