version: '3'

services:

  repeat:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file: .env.github.actions
    container_name: 'repeat-bot-tests-repeat'
    links:
      - mysql
      - redis
    volumes:
      - .:/app/
    networks:
      - repeat-bot-tests-network

  mysql:
    image: mysql:5.7.22
    container_name: 'repeat-bot-tests-mysql'
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: asterios
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tests/_data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - repeat-bot-tests-network

  redis:
    container_name: 'repeat-bot-tests-redis'
    image: redis:3.2
    ports:
      - "127.0.0.1:16379:6379/tcp"
    networks:
      - repeat-bot-tests-network

networks:
  repeat-bot-tests-network:
    driver: bridge