version: '3'

services:

  repeatt:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - ENVIRONMENT=tests
    env_file: .env.github.actions
    container_name: 'repeat-bot-tests-repeatt'
    links:
      - mysqlt
      - redist
    volumes:
      - .:/app/
    networks:
      - repeat-bot-tests-network

  mysqlt:
    image: mysql:5.7.22
    container_name: 'repeat-bot-tests-mysqlt'
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: asterios
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tests/_data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - repeat-bot-tests-network

  redist:
    container_name: 'repeat-bot-tests-redist'
    image: redis:3.2
    ports:
      - "127.0.0.1:16379:6379/tcp"
    networks:
      - repeat-bot-tests-network

networks:
  repeat-bot-tests-network:
    driver: bridge